package com.leshoraa.kore.presentation.theme

import androidx.compose.ui.graphics.Color

enum class AppPalette(val label: String, val primaryColor: Color) {
    FOREST("Forest", Color(0xFF62724A)),
    PEACH("Peach", Color(0xFFA0513B)),
    LAVENDER("Lavender", Color(0xFF6F4FA0)),
    MIDNIGHT("Midnight", Color(0xFF535F70))
}

// Forest Palette (Light)
val ForestPrimaryLight = Color(0xFF62724A)
val ForestOnPrimaryLight = Color(0xFFFFFFFF)
val ForestPrimaryContainerLight = Color(0xFFE8F5D6)
val ForestOnPrimaryContainerLight = Color(0xFF1E2216)
val ForestSecondaryLight = Color(0xFF5D6353)
val ForestOnSecondaryLight = Color(0xFFFFFFFF)
val ForestSecondaryContainerLight = Color(0xFFE2E9D6)
val ForestOnSecondaryContainerLight = Color(0xFF1A1E13)
val ForestTertiaryLight = Color(0xFF78623A)
val ForestOnTertiaryLight = Color(0xFFFFFFFF)
val ForestTertiaryContainerLight = Color(0xFFF7E6AA)
val ForestOnTertiaryContainerLight = Color(0xFF3F3000)
val ForestBackgroundLight = Color(0xFFF9FAF5)
val ForestOnBackgroundLight = Color(0xFF1A1C16)
val ForestSurfaceLight = Color(0xFFF9FAF5)
val ForestOnSurfaceLight = Color(0xFF1A1C16)
val ForestSurfaceContainerLowLight = Color(0xFFF3F5EE)
val ForestSurfaceContainerLight = Color(0xFFF0F1EB)
val ForestSurfaceContainerHighLight = Color(0xFFEAECDB)
val ForestSurfaceContainerHighestLight = Color(0xFFE4E6D5)

// Forest Palette (Dark)
val ForestPrimaryDark = Color(0xFFC8D3B4)
val ForestOnPrimaryDark = Color(0xFF2F3523)
val ForestPrimaryContainerDark = Color(0xFF474E39)
val ForestOnPrimaryContainerDark = Color(0xFFE4EFD0)
val ForestSecondaryDark = Color(0xFFC2C9B7)
val ForestOnSecondaryDark = Color(0xFF2A3225)
val ForestSecondaryContainerDark = Color(0xFF41493B)
val ForestOnSecondaryContainerDark = Color(0xFFDDE5D2)
val ForestTertiaryDark = Color(0xFFF2E3A0)
val ForestOnTertiaryDark = Color(0xFF3F3000)
val ForestTertiaryContainerDark = Color(0xFFEAD895)
val ForestOnTertiaryContainerDark = Color(0xFF3F3000)
val ForestBackgroundDark = Color(0xFF11140E)
val ForestOnBackgroundDark = Color(0xFFE2E3DC)
val ForestSurfaceDark = Color(0xFF11140E)
val ForestOnSurfaceDark = Color(0xFFE2E3DC)
val ForestSurfaceContainerLowDark = Color(0xFF1A1C16)
val ForestSurfaceContainerDark = Color(0xFF1E201A)
val ForestSurfaceContainerHighDark = Color(0xFF282B24)
val ForestSurfaceContainerHighestDark = Color(0xFF33362E)

// Peach Palette (Light)
val PeachPrimaryLight = Color(0xFFA0513B)
val PeachOnPrimaryLight = Color(0xFFFFFFFF)
val PeachPrimaryContainerLight = Color(0xFFFFDAD2)
val PeachOnPrimaryContainerLight = Color(0xFF3F0B01)
val PeachSecondaryLight = Color(0xFF77574E)
val PeachOnSecondaryLight = Color(0xFFFFFFFF)
val PeachSecondaryContainerLight = Color(0xFFFFDAD2)
val PeachOnSecondaryContainerLight = Color(0xFF2C160F)
val PeachTertiaryLight = Color(0xFF6E5D2E)
val PeachOnTertiaryLight = Color(0xFFFFFFFF)
val PeachTertiaryContainerLight = Color(0xFFFFE0A9)
val PeachOnTertiaryContainerLight = Color(0xFF241A00)
val PeachBackgroundLight = Color(0xFFFFFBFF)
val PeachOnBackgroundLight = Color(0xFF201A18)
val PeachSurfaceLight = Color(0xFFFFFBFF)
val PeachOnSurfaceLight = Color(0xFF201A18)
val PeachSurfaceContainerLowLight = Color(0xFFFAF0EE)
val PeachSurfaceContainerLight = Color(0xFFF8ECEA)
val PeachSurfaceContainerHighLight = Color(0xFFF2E6E3)
val PeachSurfaceContainerHighestLight = Color(0xFFECE0DD)

// Peach Palette (Dark)
val PeachPrimaryDark = Color(0xFFFFB4A1)
val PeachOnPrimaryDark = Color(0xFF5E2312)
val PeachPrimaryContainerDark = Color(0xFF7F3A26)
val PeachOnPrimaryContainerDark = Color(0xFFFFDAD2)
val PeachSecondaryDark = Color(0xFFE7BDB2)
val PeachOnSecondaryDark = Color(0xFF442A22)
val PeachSecondaryContainerDark = Color(0xFF5D4037)
val PeachOnSecondaryContainerDark = Color(0xFFFFDAD2)
val PeachTertiaryDark = Color(0xFFE2C48D)
val PeachOnTertiaryDark = Color(0xFF3C2E00)
val PeachTertiaryContainerDark = Color(0xFFFFE0A9)
val PeachOnTertiaryContainerDark = Color(0xFF3C2E00)
val PeachBackgroundDark = Color(0xFF201A18)
val PeachOnBackgroundDark = Color(0xFFECE0DD)
val PeachSurfaceDark = Color(0xFF201A18)
val PeachOnSurfaceDark = Color(0xFFECE0DD)
val PeachSurfaceContainerLowDark = Color(0xFF231D1B)
val PeachSurfaceContainerDark = Color(0xFF2B2220)
val PeachSurfaceContainerHighDark = Color(0xFF362C2A)
val PeachSurfaceContainerHighestDark = Color(0xFF423734)

// Lavender Palette (Light)
val LavenderPrimaryLight = Color(0xFF6F4FA0)
val LavenderOnPrimaryLight = Color(0xFFFFFFFF)
val LavenderPrimaryContainerLight = Color(0xFFEDDCFF)
val LavenderOnPrimaryContainerLight = Color(0xFF290054)
val LavenderSecondaryLight = Color(0xFF635B70)
val LavenderOnSecondaryLight = Color(0xFFFFFFFF)
val LavenderSecondaryContainerLight = Color(0xFFE9DEF8)
val LavenderOnSecondaryContainerLight = Color(0xFF1F182B)
val LavenderTertiaryLight = Color(0xFF7A536B)
val LavenderOnTertiaryLight = Color(0xFFFFFFFF)
val LavenderTertiaryContainerLight = Color(0xFFFFD7EC)
val LavenderOnTertiaryContainerLight = Color(0xFF2E1126)
val LavenderBackgroundLight = Color(0xFFFFFBFF)
val LavenderOnBackgroundLight = Color(0xFF1C1B1E)
val LavenderSurfaceLight = Color(0xFFFFFBFF)
val LavenderOnSurfaceLight = Color(0xFF1C1B1E)
val LavenderSurfaceContainerLowLight = Color(0xFFF8F4FA)
val LavenderSurfaceContainerLight = Color(0xFFF4F0F7)
val LavenderSurfaceContainerHighLight = Color(0xFFEEEAF2)
val LavenderSurfaceContainerHighestLight = Color(0xFFE8E4EC)

// Lavender Palette (Dark)
val LavenderPrimaryDark = Color(0xFFD7BAFF)
val LavenderOnPrimaryDark = Color(0xFF3F1B6E)
val LavenderPrimaryContainerDark = Color(0xFF563686)
val LavenderOnPrimaryContainerDark = Color(0xFFEDDCFF)
val LavenderSecondaryDark = Color(0xFFCDC2DB)
val LavenderOnSecondaryDark = Color(0xFF342D40)
val LavenderSecondaryContainerDark = Color(0xFF4B4358)
val LavenderOnSecondaryContainerDark = Color(0xFFE9DEF8)
val LavenderTertiaryDark = Color(0xFFEBB2D6)
val LavenderOnTertiaryDark = Color(0xFF472540)
val LavenderTertiaryContainerDark = Color(0xFFFFD7EC)
val LavenderOnTertiaryContainerDark = Color(0xFF37002B)
val LavenderBackgroundDark = Color(0xFF1C1B1E)
val LavenderOnBackgroundDark = Color(0xFFE6E1E5)
val LavenderSurfaceDark = Color(0xFF1C1B1E)
val LavenderOnSurfaceDark = Color(0xFFE6E1E5)
val LavenderSurfaceContainerLowDark = Color(0xFF1E1C21)
val LavenderSurfaceContainerDark = Color(0xFF252328)
val LavenderSurfaceContainerHighDark = Color(0xFF302E33)
val LavenderSurfaceContainerHighestDark = Color(0xFF3B383E)

// Midnight Palette (Light)
val MidnightPrimaryLight = Color(0xFF535F70)
val MidnightOnPrimaryLight = Color(0xFFFFFFFF)
val MidnightPrimaryContainerLight = Color(0xFFD7E3F7)
val MidnightOnPrimaryContainerLight = Color(0xFF101C2B)
val MidnightSecondaryLight = Color(0xFF565E71)
val MidnightOnSecondaryLight = Color(0xFFFFFFFF)
val MidnightSecondaryContainerLight = Color(0xFFDAE2F9)
val MidnightOnSecondaryContainerLight = Color(0xFF131C2B)
val MidnightTertiaryLight = Color(0xFF3B6461)
val MidnightOnTertiaryLight = Color(0xFFFFFFFF)
val MidnightTertiaryContainerLight = Color(0xFFBCECE7)
val MidnightOnTertiaryContainerLight = Color(0xFF00201E)
val MidnightBackgroundLight = Color(0xFFF9FAFF)
val MidnightOnBackgroundLight = Color(0xFF191C22)
val MidnightSurfaceLight = Color(0xFFF9FAFF)
val MidnightOnSurfaceLight = Color(0xFF191C22)
val MidnightSurfaceContainerLowLight = Color(0xFFF2F4FB)
val MidnightSurfaceContainerLight = Color(0xFFEEF0F7)
val MidnightSurfaceContainerHighLight = Color(0xFFE8EAF1)
val MidnightSurfaceContainerHighestLight = Color(0xFFE2E4EB)

// Midnight Palette (Dark)
val MidnightPrimaryDark = Color(0xFFBBC7DB)
val MidnightOnPrimaryDark = Color(0xFF253140)
val MidnightPrimaryContainerDark = Color(0xFF3B4858)
val MidnightOnPrimaryContainerDark = Color(0xFFD7E3F7)
val MidnightSecondaryDark = Color(0xFFBEC6DC)
val MidnightOnSecondaryDark = Color(0xFF283041)
val MidnightSecondaryContainerDark = Color(0xFF3E4759)
val MidnightOnSecondaryContainerDark = Color(0xFFDAE2F9)
val MidnightTertiaryDark = Color(0xFFA1D0C7)
val MidnightOnTertiaryDark = Color(0xFF053533)
val MidnightTertiaryContainerDark = Color(0xFFBCECE7)
val MidnightOnTertiaryContainerDark = Color(0xFF00201E)
val MidnightBackgroundDark = Color(0xFF111318)
val MidnightOnBackgroundDark = Color(0xFFE2E2E9)
val MidnightSurfaceDark = Color(0xFF111318)
val MidnightOnSurfaceDark = Color(0xFFE2E2E9)
val MidnightSurfaceContainerLowDark = Color(0xFF14171D)
val MidnightSurfaceContainerDark = Color(0xFF191C22)
val MidnightSurfaceContainerHighDark = Color(0xFF24272E)
val MidnightSurfaceContainerHighestDark = Color(0xFF2E323A)

// Common Colors
val ErrorRedLight = Color(0xFFBA1A1A)
val OnErrorRedLight = Color(0xFFFFFFFF)
val ErrorRedDark = Color(0xFFFFB4AB)
val OnErrorRedDark = Color(0xFF690005)
