package com.leshoraa.kore.presentation.theme

import androidx.compose.ui.graphics.Color

enum class AppPalette(val label: String, val primaryColor: Color) {
    FOREST("Forest", Color(0xFF62724A)),
    PEACH("Peach", Color(0xFFA0513B)),
    LAVENDER("Lavender", Color(0xFF6F4FA0)),
    MIDNIGHT("Midnight", Color(0xFF535F70))
}

// Forest Palette (Light)
val ForestPrimaryLight = Color(0xFF62724A)
val ForestOnPrimaryLight = Color(0xFFFFFFFF)
val ForestPrimaryContainerLight = Color(0xFFE8F5D6)
val ForestOnPrimaryContainerLight = Color(0xFF1E2216)
val ForestSecondaryLight = Color(0xFF5D6353)
val ForestOnSecondaryLight = Color(0xFFFFFFFF)
val ForestSecondaryContainerLight = Color(0xFFE2E9D6)
val ForestOnSecondaryContainerLight = Color(0xFF1A1E13)
val ForestBackgroundLight = Color(0xFFF9FAF5)
val ForestSurfaceLight = Color(0xFFF9FAF5)
val ForestSurfaceContainerLight = Color(0xFFF0F1EB)

// Forest Palette (Dark)
val ForestPrimaryDark = Color(0xFFC8D3B4)
val ForestOnPrimaryDark = Color(0xFF2F3523)
val ForestPrimaryContainerDark = Color(0xFF474E39)
val ForestOnPrimaryContainerDark = Color(0xFFE4EFD0)
val ForestSecondaryDark = Color(0xFFC2C9B7)
val ForestOnSecondaryDark = Color(0xFF2A3225)
val ForestSecondaryContainerDark = Color(0xFF41493B)
val ForestOnSecondaryContainerDark = Color(0xFFDDE5D2)
val ForestBackgroundDark = Color(0xFF1A1C18)
val ForestSurfaceDark = Color(0xFF1A1C18)
val ForestSurfaceContainerDark = Color(0xFF1E211D)

// Peach Palette (Light)
val PeachPrimaryLight = Color(0xFFA0513B)
val PeachOnPrimaryLight = Color(0xFFFFFFFF)
val PeachPrimaryContainerLight = Color(0xFFFFDAD2)
val PeachOnPrimaryContainerLight = Color(0xFF3F0B01)
val PeachSecondaryLight = Color(0xFF77574E)
val PeachOnSecondaryLight = Color(0xFFFFFFFF)
val PeachSecondaryContainerLight = Color(0xFFFFDAD2)
val PeachOnSecondaryContainerLight = Color(0xFF2C160F)
val PeachBackgroundLight = Color(0xFFFFFBFF)
val PeachSurfaceLight = Color(0xFFFFFBFF)
val PeachSurfaceContainerLight = Color(0xFFF8ECEA)

// Peach Palette (Dark)
val PeachPrimaryDark = Color(0xFFFFB4A1)
val PeachOnPrimaryDark = Color(0xFF5E2312)
val PeachPrimaryContainerDark = Color(0xFF7F3A26)
val PeachOnPrimaryContainerDark = Color(0xFFFFDAD2)
val PeachSecondaryDark = Color(0xFFE7BDB2)
val PeachOnSecondaryDark = Color(0xFF442A22)
val PeachSecondaryContainerDark = Color(0xFF5D4037)
val PeachOnSecondaryContainerDark = Color(0xFFFFDAD2)
val PeachBackgroundDark = Color(0xFF201A18)
val PeachSurfaceDark = Color(0xFF201A18)
val PeachSurfaceContainerDark = Color(0xFF2B2220)

// Lavender Palette (Light)
val LavenderPrimaryLight = Color(0xFF6F4FA0)
val LavenderOnPrimaryLight = Color(0xFFFFFFFF)
val LavenderPrimaryContainerLight = Color(0xFFEDDCFF)
val LavenderOnPrimaryContainerLight = Color(0xFF290054)
val LavenderSecondaryLight = Color(0xFF635B70)
val LavenderOnSecondaryLight = Color(0xFFFFFFFF)
val LavenderSecondaryContainerLight = Color(0xFFE9DEF8)
val LavenderOnSecondaryContainerLight = Color(0xFF1F182B)
val LavenderBackgroundLight = Color(0xFFFFFBFF)
val LavenderSurfaceLight = Color(0xFFFFFBFF)
val LavenderSurfaceContainerLight = Color(0xFFF4F0F7)

// Lavender Palette (Dark)
val LavenderPrimaryDark = Color(0xFFD7BAFF)
val LavenderOnPrimaryDark = Color(0xFF3F1B6E)
val LavenderPrimaryContainerDark = Color(0xFF563686)
val LavenderOnPrimaryContainerDark = Color(0xFFEDDCFF)
val LavenderSecondaryDark = Color(0xFFCDC2DB)
val LavenderOnSecondaryDark = Color(0xFF342D40)
val LavenderSecondaryContainerDark = Color(0xFF4B4358)
val LavenderOnSecondaryContainerDark = Color(0xFFE9DEF8)
val LavenderBackgroundDark = Color(0xFF1C1B1E)
val LavenderSurfaceDark = Color(0xFF1C1B1E)
val LavenderSurfaceContainerDark = Color(0xFF252328)

// Midnight Palette (Light)
val MidnightPrimaryLight = Color(0xFF535F70)
val MidnightOnPrimaryLight = Color(0xFFFFFFFF)
val MidnightPrimaryContainerLight = Color(0xFFD7E3F7)
val MidnightOnPrimaryContainerLight = Color(0xFF101C2B)
val MidnightSecondaryLight = Color(0xFF565E71)
val MidnightOnSecondaryLight = Color(0xFFFFFFFF)
val MidnightSecondaryContainerLight = Color(0xFFDAE2F9)
val MidnightOnSecondaryContainerLight = Color(0xFF131C2B)
val MidnightBackgroundLight = Color(0xFFF9FAFF)
val MidnightSurfaceLight = Color(0xFFF9FAFF)
val MidnightSurfaceContainerLight = Color(0xFFEEF0F7)

// Midnight Palette (Dark)
val MidnightPrimaryDark = Color(0xFFBBC7DB)
val MidnightOnPrimaryDark = Color(0xFF253140)
val MidnightPrimaryContainerDark = Color(0xFF3B4858)
val MidnightOnPrimaryContainerDark = Color(0xFFD7E3F7)
val MidnightSecondaryDark = Color(0xFFBEC6DC)
val MidnightOnSecondaryDark = Color(0xFF283041)
val MidnightSecondaryContainerDark = Color(0xFF3E4759)
val MidnightOnSecondaryContainerDark = Color(0xFFDAE2F9)
val MidnightBackgroundDark = Color(0xFF111318)
val MidnightSurfaceDark = Color(0xFF111318)
val MidnightSurfaceContainerDark = Color(0xFF191C22)

// Common Colors
val ErrorRedLight = Color(0xFFBA1A1A)
val OnErrorRedLight = Color(0xFFFFFFFF)
val ErrorRedDark = Color(0xFFFFB4AB)
val OnErrorRedDark = Color(0xFF690005)
